name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup-android
      uses: msfjarvis/setup-android@0.2
      with: 
        gradleTasks: ./gradlew assemble
    - name: Run Gradle Build Test
      run: echo Gradle Build Test
